on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: echo "Saul Razo Magallanes" 
      - run: node --version
      - run: echo "739974" 
      - uses: actions/checkout@v3
     

